/**
 * @name            Peter Thoeny / REST-FILE-I/O / REST-FILE-I/O Configuration
 * @tagline         REST-FILE-I/O API to securely read and write files in the file system
 * @description     REST-FILE-I/O is a node.js application to securely read and write files in
 *                  the file system via a REST API
 * @file            peterthoeny/rest-file-io/rest-file-io.js
 * @version         1.2.0
 * @release         2026-03-23
 * @author          Peter Thoeny, peter@thoeny.org
 * @copyright       2020-2026, Peter Thoeny, TWiki.org
 * @license         MIT
 * @repository      https://github.com/peterthoeny/rest-file-io
 * @genai           N/A
 */

// NOTE: Do not change this configuration template, copy it to /etc/ and modify that as desired

conf = {
    directories: {
        example: {
            path:       '/file/path/to/example',
            listing:    0,
            subdirs:    0,
            comment:    'anything, such as owner of directory'
        },
        tmp: {
            path:       './public/tmp',
            listing:    1, // allow file listing
            subdirs:    1, // allow subdirectories
            comment:    'sandbox for testing'
        }
    },
    binaryFiles: {
        extensions: [ 'zip', 'gz', 'tar', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'bmp', 'ico',
                      'exe', 'dll', 'so', 'dylib' ]
    },
    allowDirList:   1,      // allow directory ID listing, /api/1/directories
    allowFileList:  1,      // default allow file listing, /api/1/file/list/<directoryID>
    lockWait:       2.5,    // wait time in sec in case someone else has a lock
    lockBreak:      60,     // time in sec to hijack a stale lock
    port:           8070    // port used by the rest-file-io API
};

// EOF
